### ISSUE TITLE
Business Information

### ISSUE THREAD

**Issue by pshowell23** [HoweLohTech/home#1]
**What kind of information do we want to promote on our site?**
- Who we are?
  - Short Bios (Preston & Eric)?
- Services
  - Web Development
  - App Development
  - Tech Troubleshooting?

Any ideas are appreciated

**Comment by EEdLoh** [comment]
All that stuff sounds good to me. We can add bits for more specific stuff
when we start making it. Like a page that describes CNCBuddy or a portal to
the pages we've worked on or something like that.

**Comment by pshowell23** [comment]
@Ghandi263 just send me an email with whatever bio you want me to put on the website. Don't worry about format or anything; I'll take care of it. To

**Comment by EEdLoh** [comment]
Do we want our bios to be more professional, personal, or try to blend the two?

**Comment by pshowell23** [comment]
I would think more of a blend. Make it sound personable but also like we know what we are doing.

**Comment by EEdLoh** [comment]
Sounds good. I've been waking up early, like I usually do when I'm going to work on my app, but I've lacked motivation lately. Perhaps worrying this will be a good transition.

**Comment by pshowell23** [comment]
@Ghandi263 Give my your info and a pic!!!!!!!!!
